[project]
name = "roadtonowhere"
version = "0.1.0"
description="Check documents for broken urls"
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
]
